SPECIES = 'SPECIES'
CATALYZER_PARAMS = 'CATALYZER_PARAMS'
REACTIONS = 'REACTIONS'
SYSTEM = 'SYSTEM'
LEN_CLASSES = 'LEN_CLASSES'

SPECIES_SECTION = 'species'
CATALYZER_PARAMS_SECTION = 'catalyzer_params'
REACTIONS_SECTION = 'reactions'
SYSTEM_SECTION = 'system'
LEN_CLASSES_SECTION = 'len_classes'

CONFIG_FILE = 'config/config.ini'



DEFAULT_OUTPUT_FILE='output'

CONTAINER='Cont'

INFO='INFO'
WARNING='WARNING'
ERROR='ERROR'